### ISSUE TITLE
How to make a bot a channel?

### ISSUE THREAD

**Issue by Jkarhani** [Patrolavia/antbot#1]
Hello & thank you for your post.
Got any idea how to make a telegram channel with the bot & so that only admin can post?

**Comment by Ronmi** [comment]
You may want to visit [telegram blog](https://telegram.org/blog/channels) or [contact telegram](https://telegram.org/faq#telegram-support).

BTW, I don't know anything about "my post", I did not advertise this project anywhere. Would you mind show me some references?

**Comment by Jkarhani** [comment]
here's the post
https://github.com/Patrolavia/antbot
I am asking about a channel thru bot..thank you
